general.import = ["~/.config/alacritty/themes/nord.toml"]
# general.import = ["~/.config/alacritty/themes/atom_one_light.toml"]
general.live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 18.0

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[window]
decorations = "transparent"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 9
y = 18

[keyboard]
bindings = [
  { key = "[", mods = "Control", chars = "\u001b" },
  { key = "Slash", mods = "Control", chars = "\u001F"},
]
